package com.trabajofinal.gui;

import com.trabajofinal.controllers.AltaPoliza02Controller;
import com.trabajofinal.dto.ClienteDTO;
import com.trabajofinal.dto.VehiculoDTO;
import java.awt.image.BufferedImage;

public class AltaPoliza02 extends javax.swing.JFrame {

    private ClienteDTO cliente;
    private VehiculoDTO vehiculo;
    
    public AltaPoliza02() {}
    
    public AltaPoliza02(ClienteDTO cliente, VehiculoDTO vehiculo) {
    super("Alta de Póliza");

    // Establece un ícono transparente para evitar que se muestre el ícono de Java
    BufferedImage transparentImage = new BufferedImage(1, 1, BufferedImage.TYPE_INT_ARGB);
    setIconImage(transparentImage);

    initComponents();
    setSize(900, 600);
    setResizable(false);
    setLocationRelativeTo(null);
    setVisible(true);
    
    AltaPoliza02Controller altaPoliza02Controller = new AltaPoliza02Controller(this, cliente, vehiculo);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cmb_alta_pol02_forma_pago = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        list_alta_pol02 = new javax.swing.JList<>();
        btn_alta_poliza02_continuar = new javax.swing.JButton();
        btn_alta_poliza02_cancelar = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        cmb_alta_pol02_anio = new javax.swing.JComboBox<>();
        cmb_alta_pol02_dia = new javax.swing.JComboBox<>();
        cmb_alta_pol02_mes = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Ingrese los datos de la póliza para el cliente:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 16, 550, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/El-asegurado.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 100, 70));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Seleccione un tipo de póliza disponible:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        cmb_alta_pol02_forma_pago.setBackground(new java.awt.Color(220, 220, 220));
        cmb_alta_pol02_forma_pago.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmb_alta_pol02_forma_pago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PAGO UNICO", "MENSUAL" }));
        cmb_alta_pol02_forma_pago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_alta_pol02_forma_pagoActionPerformed(evt);
            }
        });
        jPanel3.add(cmb_alta_pol02_forma_pago, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 310, 30));

        list_alta_pol02.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        list_alta_pol02.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(list_alta_pol02);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 78, 746, 129));

        btn_alta_poliza02_continuar.setBackground(new java.awt.Color(52, 162, 224));
        btn_alta_poliza02_continuar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_alta_poliza02_continuar.setText("Continuar");
        jPanel3.add(btn_alta_poliza02_continuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 450, 100, 30));

        btn_alta_poliza02_cancelar.setBackground(new java.awt.Color(255, 128, 146));
        btn_alta_poliza02_cancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_alta_poliza02_cancelar.setText("Cancelar");
        btn_alta_poliza02_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alta_poliza02_cancelarActionPerformed(evt);
            }
        });
        jPanel3.add(btn_alta_poliza02_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 450, 100, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Forma de pago");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("/");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 10, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("Fecha de inicio de vigencia");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("Día:");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 40, 20));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setText("Mes:");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 40, 20));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setText("Año:");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 40, 20));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("/");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 10, 30));

        cmb_alta_pol02_anio.setBackground(new java.awt.Color(220, 220, 220));
        cmb_alta_pol02_anio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(cmb_alta_pol02_anio, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 70, 30));

        cmb_alta_pol02_dia.setBackground(new java.awt.Color(220, 220, 220));
        cmb_alta_pol02_dia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(cmb_alta_pol02_dia, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 70, 30));

        cmb_alta_pol02_mes.setBackground(new java.awt.Color(220, 220, 220));
        cmb_alta_pol02_mes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(cmb_alta_pol02_mes, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 70, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 906, 530));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/El-asegurado.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 100, 70));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 140, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_alta_poliza02_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alta_poliza02_cancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_alta_poliza02_cancelarActionPerformed

    private void cmb_alta_pol02_forma_pagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_alta_pol02_forma_pagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_alta_pol02_forma_pagoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AltaPoliza02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AltaPoliza02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AltaPoliza02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AltaPoliza02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AltaPoliza02().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_alta_poliza02_cancelar;
    public javax.swing.JButton btn_alta_poliza02_continuar;
    public javax.swing.JComboBox<Object> cmb_alta_pol02_anio;
    public javax.swing.JComboBox<Object> cmb_alta_pol02_dia;
    public javax.swing.JComboBox<Object> cmb_alta_pol02_forma_pago;
    public javax.swing.JComboBox<Object> cmb_alta_pol02_mes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JList<String> list_alta_pol02;
    // End of variables declaration//GEN-END:variables
}
