/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.trabajofinal.gui;

import com.trabajofinal.controllers.ConfiguracionLimiteController;
import java.awt.image.BufferedImage;

/**
 *
 * @author MATEO
 */
public class ConfiguracionLimiteDeBusqueda extends javax.swing.JFrame {

    /**
     * Creates new form ConfiguracionLimiteDeBusqueda
     */

    public ConfiguracionLimiteDeBusqueda() {
        super("Configuración de límite de búsqueda");
       // Establece un ícono transparente para evitar que se muestre el ícono de Java
        BufferedImage transparentImage = new BufferedImage(1, 1, BufferedImage.TYPE_INT_ARGB);
        setIconImage(transparentImage);
        
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        setVisible(true);
        this.limite = limite;
        ConfiguracionLimiteController configuracionLimiteController = new ConfiguracionLimiteController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        chk_config_limite_habilitar_cambio = new javax.swing.JCheckBox();
        txt_config_limite_valor_actual = new javax.swing.JLabel();
        txt_config_limite_valor_nuevo = new javax.swing.JTextField();
        btn_config_limite_guardar = new javax.swing.JButton();
        btn_config_limite_cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/configuracion.png"))); // NOI18N
        jLabel1.setText("Configuración de límite de búsqueda");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 370, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 50));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Valor actual:");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 120, 30));

        chk_config_limite_habilitar_cambio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chk_config_limite_habilitar_cambio.setBackground(new java.awt.Color(255, 255, 255));
        chk_config_limite_habilitar_cambio.setText("Nuevo valor:");
        chk_config_limite_habilitar_cambio.setToolTipText("Tildar para ingresar un nuevo valor.");
        chk_config_limite_habilitar_cambio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        chk_config_limite_habilitar_cambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_config_limite_habilitar_cambioActionPerformed(evt);
            }
        });
        jPanel2.add(chk_config_limite_habilitar_cambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 120, 30));

        txt_config_limite_valor_actual.setBackground(new java.awt.Color(204, 204, 204));
        txt_config_limite_valor_actual.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_config_limite_valor_actual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_config_limite_valor_actual.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(txt_config_limite_valor_actual, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 50, 30));

        txt_config_limite_valor_nuevo.setEditable(false);
        txt_config_limite_valor_nuevo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_config_limite_valor_nuevo.setToolTipText("Solo se pueden ingresar números de 1 o 2 dígitos.");
        jPanel2.add(txt_config_limite_valor_nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 50, 30));

        btn_config_limite_guardar.setBackground(new java.awt.Color(52, 162, 224));
        btn_config_limite_guardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_config_limite_guardar.setText("Guardar");
        btn_config_limite_guardar.setEnabled(false);
        btn_config_limite_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_config_limite_guardarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_config_limite_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 100, 30));

        btn_config_limite_cancelar.setBackground(new java.awt.Color(255, 128, 146));
        btn_config_limite_cancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_config_limite_cancelar.setText("Cancelar");
        jPanel2.add(btn_config_limite_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 100, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 400, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chk_config_limite_habilitar_cambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_config_limite_habilitar_cambioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chk_config_limite_habilitar_cambioActionPerformed

    private void btn_config_limite_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_config_limite_guardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_config_limite_guardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfiguracionLimiteDeBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfiguracionLimiteDeBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfiguracionLimiteDeBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfiguracionLimiteDeBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfiguracionLimiteDeBusqueda().setVisible(true);
            }
        });
    }
    public int limite;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_config_limite_cancelar;
    public javax.swing.JButton btn_config_limite_guardar;
    public javax.swing.JCheckBox chk_config_limite_habilitar_cambio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JLabel txt_config_limite_valor_actual;
    public javax.swing.JTextField txt_config_limite_valor_nuevo;
    // End of variables declaration//GEN-END:variables
}
