package com.trabajofinal.gui;

import com.trabajofinal.controllers.DetalleBonificacionesController;
import java.awt.image.BufferedImage;

public class DetalleBonificaciones extends javax.swing.JFrame {

    /**
       dcto_antig = poliza.getDto_antiguedad();
        dcto_mas_una_un = poliza.getDto_mas_un_vehiculo();
        dcto_pago_sem = poliza.getDto_pago_semestral();eates new form DetalleBonificaciones
     */
    
    public DetalleBonificaciones() {}
    
    public DetalleBonificaciones(Double dcto_antig, Double dcto_mas_una_un, Double dcto_pago_sem) {
        // Establece un ícono transparente para evitar que se muestre el ícono de Java
        BufferedImage transparentImage = new BufferedImage(1, 1, BufferedImage.TYPE_INT_ARGB);
        setIconImage(transparentImage);

        initComponents();
        setSize(550, 330);
        setResizable(false);
        setLocationRelativeTo(null);
        setVisible(true);
        
        DetalleBonificacionesController detalleBonificacionesController = new DetalleBonificacionesController(this, dcto_antig, dcto_mas_una_un,  dcto_pago_sem);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_det_bon_unidad = new javax.swing.JTextField();
        txt_det_bon_sem = new javax.swing.JTextField();
        txt_det_bon_ant = new javax.swing.JTextField();
        btn_detalle_bonificaciones = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pequenio.png"))); // NOI18N
        jLabel1.setText("<Detalle de bonficaciones>");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 340, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 50));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Por más de una unidad:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Por pago semestral:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("$");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, -1, -1));

        txt_det_bon_unidad.setBackground(new java.awt.Color(220, 220, 220));
        txt_det_bon_unidad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_det_bon_unidad.setFocusable(false);
        jPanel2.add(txt_det_bon_unidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 290, 30));

        txt_det_bon_sem.setBackground(new java.awt.Color(220, 220, 220));
        txt_det_bon_sem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_det_bon_sem.setFocusable(false);
        txt_det_bon_sem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_det_bon_semActionPerformed(evt);
            }
        });
        jPanel2.add(txt_det_bon_sem, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 290, 30));

        txt_det_bon_ant.setBackground(new java.awt.Color(220, 220, 220));
        txt_det_bon_ant.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_det_bon_ant.setFocusable(false);
        jPanel2.add(txt_det_bon_ant, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 290, 30));

        btn_detalle_bonificaciones.setBackground(new java.awt.Color(52, 162, 224));
        btn_detalle_bonificaciones.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_detalle_bonificaciones.setText("Continuar");
        jPanel2.add(btn_detalle_bonificaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 140, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Por antigüedad:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("$");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("$");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 550, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_det_bon_semActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_det_bon_semActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_det_bon_semActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetalleBonificaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetalleBonificaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetalleBonificaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetalleBonificaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetalleBonificaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_detalle_bonificaciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JTextField txt_det_bon_ant;
    public javax.swing.JTextField txt_det_bon_sem;
    public javax.swing.JTextField txt_det_bon_unidad;
    // End of variables declaration//GEN-END:variables
}
