/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.trabajofinal.gui;

import com.trabajofinal.controllers.DetalleCuotasController;
import com.trabajofinal.dto.CuotaDTO;
import com.trabajofinal.models.Cuota;
import java.awt.image.BufferedImage;
import java.util.List;

/**
 *
 * @author Diego
 */
public class DetalleCuotas extends javax.swing.JFrame {

    public DetalleCuotas() {
    }

    public DetalleCuotas(List<CuotaDTO> cuotas) {
        // Establece un ícono transparente para evitar que se muestre el ícono de Java
        BufferedImage transparentImage = new BufferedImage(1, 1, BufferedImage.TYPE_INT_ARGB);
        setIconImage(transparentImage);

        initComponents();
        setSize(550, 620);
        setResizable(false);
        setLocationRelativeTo(null);
        setVisible(true);

        DetalleCuotasController detalleCuotasController = new DetalleCuotasController(this, cuotas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_detalle_cuotas = new javax.swing.JButton();
        txt_det_cuota_1 = new javax.swing.JTextField();
        txt_det_cuota_2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_det_cuota_3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_det_cuota_4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_det_cuota_5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_det_cuota_6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_det_cuota_ult_pago1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_det_cuota_ult_pago2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_det_cuota_ult_pago3 = new javax.swing.JTextField();
        txt_det_cuota_ult_pago4 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_det_cuota_ult_pago5 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_det_cuota_ult_pago6 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pequenio.png"))); // NOI18N
        jLabel1.setText("<Detalle de cuotas>");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 50));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Importe cuota 1");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        btn_detalle_cuotas.setBackground(new java.awt.Color(52, 162, 224));
        btn_detalle_cuotas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_detalle_cuotas.setText("Continuar");
        jPanel2.add(btn_detalle_cuotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 470, 110, 30));

        txt_det_cuota_1.setBackground(new java.awt.Color(220, 220, 220));
        txt_det_cuota_1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_det_cuota_1.setFocusable(false);
        jPanel2.add(txt_det_cuota_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 200, 30));

        txt_det_cuota_2.setBackground(new java.awt.Color(220, 220, 220));
        txt_det_cuota_2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_det_cuota_2.setFocusable(false);
        txt_det_cuota_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_det_cuota_2ActionPerformed(evt);
            }
        });
        jPanel2.add(txt_det_cuota_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 200, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Importe cuota 2");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        txt_det_cuota_3.setBackground(new java.awt.Color(220, 220, 220));
        txt_det_cuota_3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_det_cuota_3.setFocusable(false);
        jPanel2.add(txt_det_cuota_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 200, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Importe cuota 3");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        txt_det_cuota_4.setBackground(new java.awt.Color(220, 220, 220));
        txt_det_cuota_4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_det_cuota_4.setFocusable(false);
        jPanel2.add(txt_det_cuota_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 200, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Importe cuota 4");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, 20));

        txt_det_cuota_5.setBackground(new java.awt.Color(220, 220, 220));
        txt_det_cuota_5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_det_cuota_5.setFocusable(false);
        jPanel2.add(txt_det_cuota_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 200, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Importe cuota 5");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        txt_det_cuota_6.setBackground(new java.awt.Color(220, 220, 220));
        txt_det_cuota_6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_det_cuota_6.setFocusable(false);
        jPanel2.add(txt_det_cuota_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 200, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Importe cuota 6");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        txt_det_cuota_ult_pago1.setBackground(new java.awt.Color(220, 220, 220));
        txt_det_cuota_ult_pago1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_det_cuota_ult_pago1.setFocusable(false);
        jPanel2.add(txt_det_cuota_ult_pago1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 200, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Último día de pago cuota 1");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        txt_det_cuota_ult_pago2.setBackground(new java.awt.Color(220, 220, 220));
        txt_det_cuota_ult_pago2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_det_cuota_ult_pago2.setFocusable(false);
        txt_det_cuota_ult_pago2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_det_cuota_ult_pago2ActionPerformed(evt);
            }
        });
        jPanel2.add(txt_det_cuota_ult_pago2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 200, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Último día de pago cuota 2");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Último día de pago cuota 3");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, -1, -1));

        txt_det_cuota_ult_pago3.setBackground(new java.awt.Color(220, 220, 220));
        txt_det_cuota_ult_pago3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_det_cuota_ult_pago3.setFocusable(false);
        jPanel2.add(txt_det_cuota_ult_pago3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 200, 30));

        txt_det_cuota_ult_pago4.setBackground(new java.awt.Color(220, 220, 220));
        txt_det_cuota_ult_pago4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_det_cuota_ult_pago4.setFocusable(false);
        jPanel2.add(txt_det_cuota_ult_pago4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 200, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Último día de pago cuota 4");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, -1, -1));

        txt_det_cuota_ult_pago5.setBackground(new java.awt.Color(220, 220, 220));
        txt_det_cuota_ult_pago5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_det_cuota_ult_pago5.setFocusable(false);
        txt_det_cuota_ult_pago5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_det_cuota_ult_pago5ActionPerformed(evt);
            }
        });
        jPanel2.add(txt_det_cuota_ult_pago5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 200, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Último día de pago cuota 5");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, -1, -1));

        txt_det_cuota_ult_pago6.setBackground(new java.awt.Color(220, 220, 220));
        txt_det_cuota_ult_pago6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_det_cuota_ult_pago6.setFocusable(false);
        jPanel2.add(txt_det_cuota_ult_pago6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 200, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Último día de pago cuota 6");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 550, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_det_cuota_ult_pago2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txt_det_cuota_ult_pago2ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txt_det_cuota_ult_pago2ActionPerformed

    private void txt_det_cuota_ult_pago5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txt_det_cuota_ult_pago5ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txt_det_cuota_ult_pago5ActionPerformed

    private void txt_det_cuota_2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txt_det_cuota_2ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txt_det_cuota_2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetalleCuotas.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetalleCuotas.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetalleCuotas.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetalleCuotas.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetalleCuotas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_detalle_cuotas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JTextField txt_det_cuota_1;
    public javax.swing.JTextField txt_det_cuota_2;
    public javax.swing.JTextField txt_det_cuota_3;
    public javax.swing.JTextField txt_det_cuota_4;
    public javax.swing.JTextField txt_det_cuota_5;
    public javax.swing.JTextField txt_det_cuota_6;
    public javax.swing.JTextField txt_det_cuota_ult_pago1;
    public javax.swing.JTextField txt_det_cuota_ult_pago2;
    public javax.swing.JTextField txt_det_cuota_ult_pago3;
    public javax.swing.JTextField txt_det_cuota_ult_pago4;
    public javax.swing.JTextField txt_det_cuota_ult_pago5;
    public javax.swing.JTextField txt_det_cuota_ult_pago6;
    // End of variables declaration//GEN-END:variables
}
