package com.trabajofinal.gui;

import java.awt.image.BufferedImage;
import javax.swing.JFrame;

public class ProgressWindow extends javax.swing.JFrame {

    public ProgressWindow() {
    initComponents();
    // Establece un ícono transparente para evitar que se muestre el ícono de Java
    BufferedImage transparentImage = new BufferedImage(1, 1, BufferedImage.TYPE_INT_ARGB);
    setIconImage(transparentImage);
    setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
     setUndecorated(true);
    initComponents();
    setSize(400, 180);
    setResizable(false);
    setLocationRelativeTo(null);
    setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jpb_progress = new javax.swing.JProgressBar();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(242, 242, 242));
        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1.setText("Cargando información. Aguarde...");
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 220, 30));

        jpb_progress.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpb_progress.setForeground(new java.awt.Color(52, 162, 224));
        jpb_progress.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jpb_progress.setStringPainted(true);
        jPanel1.add(jpb_progress, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 270, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 180));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    public javax.swing.JProgressBar jpb_progress;
    // End of variables declaration//GEN-END:variables
}
